### ISSUE TITLE
Please Deploy and advertise your address ahead of the sale

### ISSUE THREAD

**Issue by GriffGreen** [CanYaCoinSale/SmartContract#2]
many ICOs have had huge issues with Phishers, please make sure you advertise your address well in advance to help prevent phishing attacks:

These guys didn't heed this warning and their users lost over $100,000 sending to the wrong address:
https://github.com/MonolithDAO/token/issues/1

Please avoid the security by obscurity fallacy it is a risky game. Put the address out as soon as possible and promote it, I would suggest verifying on etherscan as well but if that worries you, its more important that the address is out in advance then anything.

Good luck and Much Love!

**Comment by canya-io** [comment]
Thanks Griff - we concur. At time of writing we are in pre-sale. Address is currently doing the rounds privately (internal team, priority contributors). The pre-sale address will be published shortly (tonight) for public use.

The main sale address will be made public several weeks before contributions start. As you can see, the public address will have a start-block so there is no reason we should keep it private. We are just holding off publishing it until we have locked down our contribution logic and a few other considerations. Once finalised & deployed, we will publish address here, and via https://canya.io main page.
